version: '3.8'
services:
  flask-app:
    build: ./automator-gpt-python-aws
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=$OPENAI_API_KEY
    # command: gunicorn -k gevent -w 1 -b 0.0.0.0:8000 main:app
    networks:
      - app-network

  react-app:
    build: ./automator-gpt-frontend-aws
    ports:
      - "8080:80"
    environment:
      - REACT_APP_BACKEND_URL=http://flask-app:8000
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
